import com.opencsv.CSVReader;

import javax.swing.*;
import java.awt.*;
import java.io.FileReader;
import java.util.Arrays;
import java.util.List;

public class MainForm {
    private JTextField fileNameTextField;
    private JButton importFileButton;
    private JTextField keyWordTextField;
    private JButton soLuongButton;
    private JButton tongTienButton;
    private JButton goiYButton;
    private JTextArea textArea1;
    private JLabel label1;
    private JLabel label2;
    private JPanel mainPanel;
    private List<String[]> dataImported;
    private XuLyDonHang xuLy;

    public MainForm() {
        importFileButton.addActionListener(e -> {
            String url = fileNameTextField.getText();
            try {
                FileReader inputFile = new FileReader(url);
                CSVReader reader = new CSVReader(inputFile);
                dataImported = reader.readAll();
                dataImported.forEach(x -> System.out.println(Arrays.toString(x)));
                xuLy = new XuLyDonHang(dataImported);
            } catch (Exception ex) {
                fileNameTextField.setText("");
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        });
        soLuongButton.addActionListener(e -> {
            String tenMatHang = keyWordTextField.getText();
            if (tenMatHang.equals("")) {
                JOptionPane.showMessageDialog(null, "Thieu keyword");
                return;
            }
            int soLuong = xuLy.getSoLuong(tenMatHang);
            textArea1.setText(Integer.toString(soLuong));
        });
        tongTienButton.addActionListener(e -> {
            String tenNguoiMua = keyWordTextField.getText();
            if (tenNguoiMua.equals("")) {
                JOptionPane.showMessageDialog(null, "Thieu keyword");
                return;
            }
            int tongTien = xuLy.getTongTien(tenNguoiMua);
            textArea1.setText(Integer.toString(tongTien));
        });
        goiYButton.addActionListener(e -> {
            String tenMatHang = keyWordTextField.getText();
            if (tenMatHang.equals("")) {
                JOptionPane.showMessageDialog(null, "Thieu keyword");
                return;
            }
            List<String> result = xuLy.getGoiY(tenMatHang);
            StringBuilder text = new StringBuilder();
            for (String x : result) {
                text.append(x).append("\n");
            }
            textArea1.setText(text.toString());
        });
    }

    public static void run() {
        JFrame frame = new JFrame("MainForm");
        frame.setContentPane(new MainForm().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(500, 300));
        mainPanel.setPreferredSize(new Dimension(500, 300));
        label1 = new JLabel();
        label1.setText("Import data");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(label1, gbc);
        fileNameTextField = new JTextField();
        fileNameTextField.setName("fileNameTextField");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(fileNameTextField, gbc);
        importFileButton = new JButton();
        importFileButton.setText("Import file");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(importFileButton, gbc);
        label2 = new JLabel();
        label2.setText("Keyword");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(label2, gbc);
        keyWordTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(keyWordTextField, gbc);
        soLuongButton = new JButton();
        soLuongButton.setText("So luong");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(soLuongButton, gbc);
        tongTienButton = new JButton();
        tongTienButton.setText("Tong tien");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(tongTienButton, gbc);
        goiYButton = new JButton();
        goiYButton.setText("Goi y");
        goiYButton.setMnemonic('G');
        goiYButton.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(goiYButton, gbc);
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        textArea1.setMinimumSize(new Dimension(50, 50));
        textArea1.setPreferredSize(new Dimension(50, 100));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 10, 0);
        mainPanel.add(textArea1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
